minetest-mods/nether

init.lua

Portals were lacking particle spawners, this issue was introduced by 0b6925f4b1f. Fix tested in 4.17.1 and 5.1-dev
Any chance you can remember what "old bug id #21" was, @sofar ?
I've changed it from calling the deprecated form of `add_particlespawner(…)` to the one that takes a particlespawner definition as a parameter, but that wasn't really the fix - undoing 0b6925f4b1f also fixes the particle spawners.

Fix portal particle spawners

---

init.lua

Looks like some sort of merge problem:
32affba6 re-registered stairs which have already been registered 20 lines earlier in the code, and it registered them as "brick" instead of "nether_brick", causing the netherbrick stairs to replace Minetest's default:brick stairs. The rest of 32affba6 has already been unrolled in 7a0e52da, but the stairs bug remained.
Fixing this bug means brick stairs will appear in the Nether anywhere a player has previously laid netherbrick stairs, however generated dungeons are fine as the dungeon generation does not currently create netherbrick stairs.

Unroll 32affba6 (stairs)

---

init.lua

logs of my server ( username removed)
```
2020-01-05 08:15:15: ACTION[Server]: ... leaves game. List of players: 
2020-01-05 08:15:17: ACTION[Main]: Server: Shutting down
2020-01-05 08:15:18: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'nether' in callback environment_Step(): /root/.minetest/mods/nether/init.lua:300: attempt to index local 'objpos' (a nil value)
2020-01-05 08:15:18: ERROR[Main]: stack traceback:
2020-01-05 08:15:18: ERROR[Main]: 	/root/.minetest/mods/nether/init.lua:300: in function 'func'
2020-01-05 08:15:18: ERROR[Main]: 	...c709f/usr/bin/../share/minetest/builtin/common/after.lua:20: in function <...c709f/usr/bin/../share/minetest/builtin/common/after.lua:5>
2020-01-05 08:15:18: ERROR[Main]: …
```

Fixed a bug where players quit when teleporting

---

init.lua

The second argument of minetest.settings:get_bool is the default value (for when the configuration value is not set). Remove the superfluous `or nether.NETHER_REALM_ENABLED` which rendered the config option useless, because it always forced the variable to true.

Fix logic bug in parsing of nether_realm_enabled

---

portal_api.lua
portal_api.txt

Purely cosmetic
Portal schematics include facedir information for when new portals are spawned with frame nodes that use facedir or colorfacedir.
Will allow the creation of chiselled/carved portal stone nodes - better ones than this proof-of-concept texture:

Add facedir support to Portals API

---

init.lua
mapgen.lua
mapgen_decorations.lua
mapgen_nobiomes.lua
settingtypes.txt

This moves the original mapgen code to [`mapgen_nobiomes.lua`](https://github.com/minetest-mods/nether/blob/34d54abce642885f92aeb4424877dad9b5c591ae/mapgen_nobiomes.lua), and provides an MT5 biomes-based equivalent mapgen in [`mapgen.lua`](https://github.com/minetest-mods/nether/blob/34d54abce642885f92aeb4424877dad9b5c591ae/mapgen.lua). Both mapgens use paramat's cave noise. The old mapgen is loaded in v6 worlds and versions of MT prior to 5.1
My own reason for the change is I want to add a lot to the Nether, and getting it working with biomes API, ores API etc provides a better platform to build on.
However, this PR provides many other advantages:
* mapgen is ~20% faster *...(at least until more features get added)*.
* Dungeons are preserved. It's not perfect, but the original code was …

Switch mapgen to using biomes (still with backwards compatibility)

---

mapgen.lua
mapgen_decorations.lua

I'll merge this myself eventually, so this PR is more of a heads-up and opportunity for anyone to comment, object, or tune.
The biomes-based mapgen creates the same amount of lava ores as the original nether mapgen, but it doesn't have the same issue of chunk emerge order causing lava ores in the overdraw regions to randomly get removed. This adjustment will hopefully balance that difference out a little. (see also paramat's comment about [why too much lava isn't necessarily desireable](https://github.com/minetest-mods/nether/issues/4#issuecomment-506986647), plus I'm also hoping to add [a new region](https://forum.minetest.net/viewtopic.php?p=375637#p375637) to the nether at some point with lava seas - so people can get their lava-pool fix that way)
Also makes glowstone stalactites a bit …

Reduce lava in biomes-based mapgen

---

.luacheckrc
init.lua
mapgen.lua
mapgen_nobiomes.lua
portal_api.lua
portal_api.txt
portal_examples.lua

Fixes #26 
I've tested this a little, but I may test it more
~~It also raises the priority of an old bug - the volume that is checked before a portal is created does not exactly match the volume of nodes that are altered by placing the portal schematic. I think it's only out by a block tho.~~ Now fixed as part of this PR in 
ac557cf 
There's a very minor issue where the portal target is checked when the portal is ignited, but the remote portal schematic is not placed until someone walks through the portal. So if a protection is placed after the portal is ignited but before someone walks through it for the first time, then the protection will get ignored. I'll file that in the "don't care" basket ;)

Respect protected areas when spawning remote portals

---

init.lua
portal_api.lua

This branch is forked off the protection support branch, so the diff will be messy until that gets merged. Best to just look at commit 9260625 
Adds a debug-printing function that understands vectors etc. and reduces evaluation (such as string composing) when debugging is turned off. It works like string.format(), treating the message as a format string.
nils, tables, and vectors passed as arguments to nether.debug() are converted to strings and can be included inside the message with %s

Add a nether.debug() function for printing debug info

---

init.lua
portal_api.lua
portal_api.txt

Portals will now fail to ignite instead of defaulting to a fallback depth of (starty - 256) when no good target area can be found.
The search depth is also increased from (starty - 256) to (starty - 646)
This is to properly handle large protected areas that are sometimes set up at spawn - see issue #26
"Mysterious forces prevented you from opening that portal. Please try another location" is sent as a chat message to the player if no target destination can be found. (the ignition_failure_sound is also played)

Handle large protected depths

---

.luacheckrc
depends.txt
init.lua
locale/nether.fr.tr
locale/template.txt
mapgen.lua
mapgen_mantle.lua
mod.conf

Add appropriate/atmospheric distance fog to the nether, via [climate_api](https://github.com/t-affeldt/climate_api) mod to avoid conflicting with other mods.
Any game or server with climate_api mod installed will be expecting climate_api to take control of sky values.
Skylayer is another mod which could perform that role, but supporting it will require a little more code - see comments in code.
There's also some related refactoring.
My screenshots are often too dark when displayed on other devices, so the shot above probably isn't representative of how it looks in-game.

climate_api support - add distance fog

---

init.lua
mod.conf
nodes.lua

Fixes #41, #42, #43
I'll merge this eventually if there are no comments.
Any thoughts on the "fix" for Ethereal? Is there a better way to document why it's in the dependencies now, currently the only explanation is in the commit?
---
Sorry for the delay on these - they were good error reports.
I'm battling a chronic Valheim addiction :)

Feature/fix issues #41 #42 #43

---

portal_api.lua

fixes a nil bug in portal_api.lua where nodedef.is_ground_content isn't available.

fix nil bug in portal_api.lua

---

init.lua
mapgen.lua
mapgen_mantle.lua
nether_api.txt
nodes.lua
portal_api.lua
portal_api.txt
portal_examples.lua

Fixes bug with wrong new_y_min when shifting a biome below the nether floor, and makes the ShiftExistingBiomes function available to other mods via the nether global, since it's not a simple function and biomes would also need to be shifted if another mod wants to add a second nether layer.
I realised ShiftExistingBiomes() would need to be exposed [while responding to ywwv's suggestion of adding more layers](https://forum.minetest.net/viewtopic.php?p=389760#p389760), however it's not clear whether anyone will ever care to do that, so it's hardly urgent, but also pretty minor.
~~'ll merge this in eventually if there's no comments or change requests.~~ I'll first implement improvements raised by SmallJoker (now done)

Make ShiftExistingBiomes available via API

---

README.md
locale/nether.fr.tr
locale/template.txt
nodes.lua

Fixes #56, and adds netherbrick rails (for consistency with MTG) ~~if the fences API is found.~~
Using the MTG fence system adds interop between different fence types, and support for the "Tall fences and walls" option.
I've left the nether's register_craft() call unchanged, it overrides the recipe that default.register_fence() registers, granting 6 fences per crafting instead of MTG's 4.

Use Minetest_game fences API if it's available

---

init.lua

I'll merge this in a couple of days if nobody has commented or merged it themselves
---
Climate_API can help a little with a lighting problem recently raised on the forums, so I went to get a screenshot of nether with climate_api mod running... and it didn't work.
The mantle and geode skys were working correctly, but not the sky in the main nether area - it would always switch back to stars. This fix was found by process of elimination, so I don't know why climate_api doesn't accept "nether:nether" as a unique weather name identifier, or how this issue wasn't noticed earlier (did something change?).
climate_api's api_doc.md file says the name:
>should be prefixed with the mod's name in a way that could look like ``mymod:awesome_weather``. This name should only be used once.
so perhaps …

fix the sky in the nether caverns when using climate_api

---

locale/nether.fr.tr
locale/template.txt
nodes.lua

I noticed it was improperly named.

A fix for Netherrack slab being called Deep Netherrack slab

---

mapgen.lua

(Replaces PR #69 with a better workaround from PR feedback by SmallJoker)
Hides bug #51 - the node_stone of the biome appears in the whole chunk under the Nether, so make nether:native_mapgen look the same as default:stone, and drop whatever default:stone drops.
The approach improves existing badly generated worlds, and any on_generate() bugs that might happen in the future.

Hide unknown nodes under the nether bug

---

portal_api.lua

This is needed to work with telemosaic since telemosaic depends on `on_rightclick` being called on beacon blocks when wielding a mese crystal fragment.

call old `on_place` when not clicking on portal material.

---

tools.lua

This PR eliminates the one issue I had with this mod: Eternal Lightstaff wearing out even in creative mode. Like, come on, it's so satisfying to use!
On top of that, the more traditional `add_wear` method here is replaced with `add_wear_by_uses`. Tested, no change in functionality. Just a little code quality improvement.

Don't wear out lightstaff in creative and replace add_wear with add_wear_by_uses

---

nodes.lua

Unfortunately `[fill` is only available in v5.8 clients onwards, so if anybody has a better idea? Should we break out a 1x1.png ?
See issue #81

Fix Particle errors #81
